version: '3'
services:
  ubuntu:
    image: ubuntu:latest
    command: tail -f /dev/null
    tty: true
    stdin_open: true
    volumes:
      - ./:/home/
    networks:
      - mynetwork

networks:
  mynetwork:
